

export const skills = [
    {
        name:"React",
        icon:'/icons/react.svg',
        category:"frontEnd",
        level: "",
        color: "",
    },
    {
        name:"JavaScript",
        icon:'/icons/javascript.svg',
        category:"frontEnd"
    },
    {
        name:"Html",
        icon:'/icons/html-5.svg',
        category:"frontEnd"
    },
    {
        name:"Css",
        icon:'/icons/css.svg',
        category:"frontEnd"
    },
    {
        name:"TypeScript",
        icon:'/icons/typescript.svg',
        category:"frontEnd"
    },
    {
        name:"Git",
        icon:'/icons/git.svg',
        category:"frontEnd"
    },
    {
        name:"PHP",
        icon:'/icons/php.svg',
        category:"backEnd"
    },
    {
        name:"NextJs",
        icon:'/icons/nextjs.svg',
        category:"frontEnd"
    },
    {
        name:"MySql",
        icon:'/icons/mysql.svg',
        category:"backEnd"
    },
    {
        name:"TailWind",
        icon:'/icons/tailwind.svg',
        category:"frontEnd"
    },
    {
        name:"Redux",
        icon:'/icons/redux.svg',
        category:"frontEnd"
    },
    {
        name:"MongoDb",
        icon:'/icons/mongodb.svg',
        category:"backEnd"
    },
    {
        name:"Supabase",
        icon:'/icons/supabase.png',
        category:"backEnd"
    },
    {
        name:"C",
        icon:'/icons/c.png',
        category:"backEnd"
    },
    {
        name:"Java",
        icon:'/icons/java.svg',
        category:"backEnd"
    },
]